export const GET_PRICES = 'GET_PRICES'
export const ADD_PRICE = 'ADD_PRICE'
export const PRICE_ERROR = 'PRICE_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_LOADING = 'SET_LOADING'